/* ============================================================
   HOTEL AVA – SHARED DATA
   Shared room data used by Home and Checkout pages
   ============================================================ */

const rooms = [
  {
    id: 1,
    name: "Ava Deluxe",
    type: "deluxe",
    sqm: 32,
    bed: "King Bed",  
    maxGuests: 2,
    image: "images/room-deluxe.png",
    oldPrice: 5500,
    price: 4200,
    rating: 9.2,
    ratingLabel: "Superb",
    reviewCount: 124,
    available: 5,
    aiScore: 95,
    amenities: ["wifi", "tv", "wind", "coffee"],
    amenityLabels: ["WiFi", "TV", "AC", "Minibar"],
    hasDeal: true,
    dealText: "20% OFF Today",
    pastStay: "March 2024",
    description: "Elegant and spacious with stunning city views of Malate."
  },
  {
    id: 2,
    name: "Ava Deluxe Twin",
    type: "deluxe",
    sqm: 32,
    bed: "Twin Beds",
    maxGuests: 2,
    image: "images/room-premium.png",
    oldPrice: 4800,
    price: 3800,
    rating: 8.8,
    ratingLabel: "Excellent",
    reviewCount: 89,
    available: 8,
    aiScore: 82,
    amenities: ["wifi", "tv", "wind", "coffee"],
    amenityLabels: ["WiFi", "TV", "AC", "Minibar"],
    hasDeal: false,
    dealText: "",
    pastStay: null,
    description: "Comfortable twin bedding perfect for friends or colleagues."
  },
  {
    id: 3,
    name: "Ava Premier",
    type: "deluxe",
    sqm: 38,
    bed: "King Bed",
    maxGuests: 2,
    image: "images/room-suite.png",
    oldPrice: 8000,
    price: 6500,
    rating: 9.0,
    ratingLabel: "Superb",
    reviewCount: 67,
    available: 3,
    aiScore: 88,
    amenities: ["wifi", "tv", "wind", "bath"],
    amenityLabels: ["WiFi", "Smart TV", "AC", "Bathtub"],
    hasDeal: true,
    dealText: "Best Value",
    pastStay: null,
    description: "Upgraded boutique comfort with premium amenities and extra space."
  },
  {
    id: 4,
    name: "Ava Executive",
    type: "suite",
    sqm: 45,
    bed: "King Bed",
    maxGuests: 3,
    image: "images/room-premium.png",
    oldPrice: 11000,
    price: 9000,
    rating: 9.4,
    ratingLabel: "Exceptional",
    reviewCount: 52,
    available: 2,
    aiScore: 92,
    amenities: ["wifi", "tv", "bath", "utensils"],
    amenityLabels: ["WiFi", "Smart TV", "Bathtub", "Dining"],
    hasDeal: true,
    dealText: "Special Offer",
    pastStay: "January 2025",
    description: "Spacious suite with separate living area and premium Filipino hospitality."
  },
  {
    id: 5,
    name: "Ava Grand Suite",
    type: "suite",
    sqm: 55,
    bed: "King Bed",
    maxGuests: 3,
    image: "images/room-suite.png",
    oldPrice: 12500,
    price: 11000,
    rating: 9.6,
    ratingLabel: "Exceptional",
    reviewCount: 38,
    available: 1,
    aiScore: 78,
    amenities: ["wifi", "tv", "bath", "wine"],
    amenityLabels: ["WiFi", "Smart TV", "Bathtub", "Rooftop Lounge"],
    hasDeal: true,
    dealText: "12% OFF",
    pastStay: null,
    description: "Our signature suite with rooftop bar access and butler service."
  },
  {
    id: 6,
    name: "Ava Penthouse",
    type: "suite",
    sqm: 80,
    bed: "King Bed",
    maxGuests: 4,
    image: "images/room-presidential.png",
    oldPrice: null,
    price: 12000,
    rating: 9.8,
    ratingLabel: "Outstanding",
    reviewCount: 15,
    available: 0,
    aiScore: 65,
    amenities: ["wifi", "tv", "utensils", "bell-ring"],
    amenityLabels: ["WiFi", "Smart TV", "Private Dining", "Butler"],
    hasDeal: false,
    dealText: "",
    pastStay: null,
    description: "The ultimate boutique experience with panoramic views of Manila Bay."
  }
];
